### ISSUE TITLE
Error handling when given an invalid image

### ISSUE THREAD

**Issue by kaitoii11** [Medha-B/XitoSBML#15]
When the input argument file does not exist, XitoSMBLCLI outputs an error.
We should check if the input file exists or not

```Java
Unsupported format or not found
java.lang.NullPointerException
	at jp.ac.keio.bio.fun.xitosbml.image.Interpolator.getInfo(Interpolator.java:102)
	at jp.ac.keio.bio.fun.xitosbml.image.Interpolator.interpolate(Interpolator.java:117)
	at jp.ac.keio.bio.fun.xitosbml.image.Interpolator.interpolate(Interpolator.java:168)
	at jp.ac.keio.bio.fun.xitosbml.cli.CliMainImgSpatial.computeImg(CliMainImgSpatial.java:129)
	at jp.ac.keio.bio.fun.xitosbml.cli.CliMainImgSpatial.runCli(CliMainImgSpatial.java:64)
	at jp.ac.keio.bio.fun.xitosbml.cli.CliRun.RunXitosbml(CliRun.java:27)
	at jp.ac.keio.bio.fun.xitosbml.cli.CliRun.call(CliRun.java:56)
	at jp.ac.keio.bio.fun.xitosbml.cli.CliRun.call(CliRun.java:1)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at jp.ac.keio.bio.fun.xitosbml.cli.CliRun.main(CliRun.java:62)
```

**Comment by Medha-B** [comment]
Please see the pull request https://github.com/Medha-B/XitoSBML/pull/19 for this issue.
